export const countryCodes = [
  { name: "العراق", code: "+964", flag: "🇮🇶" },
  { name: "السعودية", code: "+966", flag: "🇸🇦" },
  { name: "الإمارات", code: "+971", flag: "🇦🇪" },
  { name: "الكويت", code: "+965", flag: "🇰🇼" },
  { name: "قطر", code: "+974", flag: "🇶🇦" },
  { name: "عمان", code: "+968", flag: "🇴🇲" },
  { name: "البحرين", code: "+973", flag: "🇧🇭" },
  { name: "مصر", code: "+20", flag: "🇪🇬" },
  { name: "الأردن", code: "+962", flag: "🇯🇴" },
  { name: "لبنان", code: "+961", flag: "🇱🇧" },
  { name: "سوريا", code: "+963", flag: "🇸🇾" },
  { name: "فلسطين", code: "+970", flag: "🇵🇸" },
  { name: "اليمن", code: "+967", flag: "🇾🇪" },
  { name: "المغرب", code: "+212", flag: "🇲🇦" },
  { name: "الجزائر", code: "+213", flag: "🇩🇿" },
  { name: "تونس", code: "+216", flag: "🇹🇳" },
  { name: "ليبيا", code: "+218", flag: "🇱🇾" },
  { name: "السودان", code: "+249", flag: "🇸🇩" },
  { name: "تركيا", code: "+90", flag: "🇹🇷" },
  { name: "الولايات المتحدة", code: "+1", flag: "🇺🇸" },
  { name: "المملكة المتحدة", code: "+44", flag: "🇬🇧" },
  { name: "ألمانيا", code: "+49", flag: "🇩🇪" },
  { name: "فرنسا", code: "+33", flag: "🇫🇷" },
  { name: "إيران", code: "+98", flag: "🇮🇷" },
];
